SELECT * 
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01'
--BUSCA UMA INFORMAÇÃO ENTRE UMA COISA INICIAL E FINAL

SELECT*
FROM Person.Person
WHERE BusinessEntityID IN (2,7,13)
--BUSCA A INFORMAÇÃO QUE ESTÁ DENTRO DE UM RANGE NESSE CASO DENTRO DAS ESPECIFICAÇÕES

SELECT*
FROM Person.Person
WHERE FirstName LIKE 'OVI%'
/*SERVE PARA BUSCAS APROCIMADAS ONDE PODEMOS USAR O 
%OVI BUSCAR ESSE PADRÃO NO INICIO DA FRASE
%OVI% BUSCAR ESSE PADRÃO NO MEIO DA FRASE
OVI% BUSCAR ESSE PADRÃO NO FINAL DA FRASE
%OVI_BUSCAR ESSE PADRÃO NO INICIO DA FRASE MAS O _ LIMITA EM UM CARACTER QUE PODE EXISTIR DEPOIS DO PADRÃO

*** O LIKE NÃO É CASE SENCITIVE
*/